services:
  # Base Docker image requires running `./mach taskgraph load-image debian12-amd64-build:latest`
  build-repair:
    # TO minimize rebuilding use `DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build -t build-repair-debian-base -f docker/build_repair/Dockerfile .`
    # image: build-repair-debian-base
    build:
      context: .
      dockerfile: docker/build_repair/Dockerfile
    volumes:
      - .:/app # live code editing
      - ${FIREFOX_GIT_REPO}:/workspace/firefox # Firefox repo
      - build-repair-tmp:/tmp/build_repair_worktrees
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY} # for weave
      - FIREFOX_GIT_REPO=/workspace/firefox
volumes:
  build-repair-tmp:
