"""Add acting_capacity field to ReviewRequest.

Revision ID: 53f024d8e601
Revises: 579adfa85713
Create Date: 2026-02-19 15:34:59.395075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53f024d8e601"
down_revision: Union[str, Sequence[str], None] = "579adfa85713"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_requests",
        sa.Column(
            "acting_capacity",
            sa.Enum("AUTHOR", "REVIEWER", "PARTICIPANT", name="acting_capacity_enum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_requests", "acting_capacity")
    # ### end Alembic commands ###
