"""Add index for platform comment id.

Revision ID: 579adfa85713
Revises: a6b26ceccd9f
Create Date: 2026-02-18 11:27:56.953437

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "579adfa85713"
down_revision: Union[str, Sequence[str], None] = "a6b26ceccd9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_generated_comments_platform_comment_id",
        "generated_comments",
        ["platform_comment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_generated_comments_platform_comment_id", table_name="generated_comments"
    )
    # ### end Alembic commands ###
