"""Rename RETRYING to RETRY_PENDING and remove COMPLETED status.

Revision ID: 714c920ab85b
Revises: f396ea3231a9
Create Date: 2026-02-21 15:20:31.544304

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "714c920ab85b"
down_revision: Union[str, Sequence[str], None] = "f396ea3231a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="review_status_enum",
        new_values=[
            "PENDING",
            "PROCESSING",
            "RETRY_PENDING",
            "PUBLISHED",
            "FAILED",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="review_requests",
                column_name="status",
            )
        ],
        enum_values_to_rename=[("RETRYING", "RETRY_PENDING")],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="review_status_enum",
        new_values=[
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "PUBLISHED",
            "FAILED",
            "RETRYING",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="review_requests",
                column_name="status",
            )
        ],
        enum_values_to_rename=[("RETRY_PENDING", "RETRYING")],
    )
    # ### end Alembic commands ###
