"""Initial Schema.

Revision ID: a6b26ceccd9f
Revises:
Create Date: 2026-02-14 13:53:07.332019

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6b26ceccd9f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("PHABRICATOR", "GITHUB", name="platform_enum"),
            nullable=False,
        ),
        sa.Column("revision_id", sa.Integer(), nullable=True),
        sa.Column("diff_id", sa.Integer(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("repo", sa.String(), nullable=True),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("sha", sa.String(length=40), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "PUBLISHED",
                "FAILED",
                name="review_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_requests_github_unique",
        "review_requests",
        ["owner", "repo", "pr_number", "sha"],
        unique=True,
        postgresql_where=sa.text("platform = 'GITHUB'"),
    )
    op.create_index(
        "ix_review_requests_phabricator_unique",
        "review_requests",
        ["revision_id", "diff_id"],
        unique=True,
        postgresql_where=sa.text("platform = 'PHABRICATOR'"),
    )
    op.create_table(
        "generated_comments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_request_id", sa.BigInteger(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("on_new", sa.Boolean(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("platform_comment_id", sa.BigInteger(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_request_id"], ["review_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_comment_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "feedback_type",
            sa.Enum("UP", "DOWN", name="feedback_type_enum"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column(
            "acting_capacity",
            sa.Enum("AUTHOR", "REVIEWER", "PARTICIPANT", name="acting_capacity_enum"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["generated_comment_id"], ["generated_comments.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "generated_comment_id", "user_id", name="uq_feedback_comment_user"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    op.drop_table("generated_comments")
    op.drop_index(
        "ix_review_requests_phabricator_unique",
        table_name="review_requests",
        postgresql_where=sa.text("platform = 'PHABRICATOR'"),
    )
    op.drop_index(
        "ix_review_requests_github_unique",
        table_name="review_requests",
        postgresql_where=sa.text("platform = 'GITHUB'"),
    )
    op.drop_table("review_requests")
    # ### end Alembic commands ###
