"""Drop task_id.

Revision ID: f396ea3231a9
Revises: 30a5eeb5f400
Create Date: 2026-02-21 07:27:49.712489

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "f396ea3231a9"
down_revision: Union[str, Sequence[str], None] = "30a5eeb5f400"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="review_status_enum",
        new_values=[
            "PENDING",
            "PROCESSING",
            "COMPLETED",
            "PUBLISHED",
            "FAILED",
            "RETRYING",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="review_requests",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("review_requests", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_requests",
        sa.Column("task_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="review_status_enum",
        new_values=["PENDING", "PROCESSING", "COMPLETED", "PUBLISHED", "FAILED"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="review_requests",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
