import logging
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import JSONResponse
from sqlalchemy import insert, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import verify_external_api_key
from app.database.connection import get_db
from app.database.models import Feedback, GeneratedComment, ReviewRequest
from app.enums import Platform
from app.schemas.feedback import FeedbackCreate, FeedbackResponse

logger = logging.getLogger(__name__)

router = APIRouter(
    tags=["feedback"],
    dependencies=[Depends(verify_external_api_key)],
)


@router.post(
    "/feedback",
    response_model=FeedbackResponse,
)
async def submit_feedback(
    request: FeedbackCreate,
    db: Annotated[AsyncSession, Depends(get_db)],
):
    """Submit feedback on a review comment."""
    stmt = (
        select(GeneratedComment.id)
        .join(ReviewRequest)
        .where(
            GeneratedComment.platform_comment_id == request.comment_id,
            ReviewRequest.platform == Platform.PHABRICATOR,
        )
    )

    generated_commit_id = await db.scalar(stmt)
    if generated_commit_id is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail="The comment does not seem to be generated by Review Helper",
        )

    stmt = insert(Feedback).values(
        generated_comment_id=generated_commit_id,
        feedback_type=request.feedback_type,
        user_id=request.user_id,
        user_name=request.user_name,
    )

    try:
        await db.execute(stmt)
    except IntegrityError as e:
        # We allow updating feedback, so only raise if other integrity error
        if "uq_feedback_comment_user" not in str(e.orig):
            raise e

        logger.info(
            "Feedback from user %s on comment %s exists, updating",
            request.user_id,
            generated_commit_id,
        )

        await db.rollback()

        stmt = (
            update(Feedback)
            .values(feedback_type=request.feedback_type)
            .where(
                Feedback.generated_comment_id == generated_commit_id,
                Feedback.user_id == request.user_id,
            )
        )

        await db.execute(stmt)

    return JSONResponse(
        {
            "message": (
                "Feedback submitted successfully."
                if stmt.is_insert
                else "Feedback updated successfully."
            )
        }
    )
