version: 1
tasks:
  - ID: check-component
    created: {$fromNow: ''}
    deadline: {$fromNow: '12 hours'}
    expires: {$fromNow: '1 week'}
    provisionerId: proj-bugbug
    workerType: batch
    payload:
      maxRunTime: 3600
      image: mozilla/bugbug-base
      command:
        - bugbug-check
        - component

    routes:
      - notify.email.release-mgmt-analysis@mozilla.com.on-failed
      - notify.irc-channel.#bugbug.on-failed
    metadata:
      name: bugbug check component
      description: bugbug check component
      owner: release-mgmt-analysis@mozilla.com
      source: https://github.com/mozilla/bugbug/raw/master/infra/check-pipeline.yml

  - ID: shadow-scheduler-stats
    created: {$fromNow: ''}
    deadline: {$fromNow: '12 hours'}
    expires: {$fromNow: '1 week'}
    provisionerId: proj-bugbug
    workerType: batch
    payload:
      maxRunTime: 43200
      image: mozilla/bugbug-base
      command:
        - bugbug-shadow-scheduler-stats
        - "28"

      artifacts:
        public/shadow_scheduler_stats.json.zst:
          path: /data/shadow_scheduler_stats.json.zst
          type: file
        public/shadow_scheduler_stats.json.version:
          path: /data/shadow_scheduler_stats.json.version
          type: file
    scopes:
      - auth:aws-s3:read-write:communitytc-bugbug/*
    routes:
      - notify.email.release-mgmt-analysis@mozilla.com.on-failed
      - notify.irc-channel.#bugbug.on-failed
      - index.project.bugbug.shadow_scheduler_stats.latest
    metadata:
      name: bugbug shadow scheduler stats
      description: bugbug shadow scheduler stats
      owner: release-mgmt-analysis@mozilla.com
      source: https://github.com/mozilla/bugbug/raw/master/infra/check-pipeline.yml
