FROM python:3.12.7-slim

# Setup dependencies in a cacheable step
ADD spawn_pipeline_requirements.txt /code/

RUN pip install --disable-pip-version-check --quiet --no-cache-dir -r /code/spawn_pipeline_requirements.txt

ADD spawn_pipeline.py /code

ADD *-pipeline.yml /code/

CMD python /code/spawn_pipeline.py
