FROM python:3.7.3-slim

# Setup dependencies in a cacheable step
COPY requirements.txt /requirements.txt
RUN apt-get update && \
		apt-get install -y --no-install-recommends gcc g++ libgomp1 && \
		pip install --disable-pip-version-check --no-cache-dir -r /requirements.txt && \
		apt-get remove -y gcc g++ && \
		apt-get autoremove -y && \
		rm -rf /var/lib/apt/lists/*

COPY . /tmp/bugbug
RUN pip install --disable-pip-version-check --no-cache-dir /tmp/bugbug
