FROM mozilla/bugbug-base:latest

# Setup dependencies in a cacheable step
ADD extra-nlp-requirements.txt /

RUN apk update && \
    apk add --no-cache gcc g++ libgomp && \
    pip install --disable-pip-version-check --no-cache-dir --no-binary :all: srsly==0.1.0 blis==0.4.1 && \
    pip install --disable-pip-version-check --no-cache-dir --verbose -r /extra-nlp-requirements.txt

RUN python -m spacy download en_core_web_sm && \
    apk del gcc g++ libgomp
