FROM python:3.7.3

COPY requirements.txt /code/bugbug/

RUN pip install --disable-pip-version-check --no-cache-dir -r /code/bugbug/requirements.txt

COPY . /code/bugbug/

RUN pip install /code/bugbug/