FROM python:3.7.3-slim

# Setup dependencies in a cacheable step
ADD spawn_pipeline_requirements.txt /code/

RUN pip install --disable-pip-version-check --no-cache-dir -r /code/spawn_pipeline_requirements.txt

ADD spawn_pipeline.py /code
ADD trigger_again.py /code

ADD data-pipeline.yml /code
ADD check-pipeline.yml /code
ADD annotate-pipeline.yml /code

CMD python /code/spawn_pipeline.py
