[project]
name = "bugbug-mcp-code-review"
version = "0.1.0"
description = "MCP server for BugBug code review functionality"
requires-python = ">=3.12"
dependencies = [
    "bugbug>=0.0.590",
    "fastmcp>=2.12.0",
]
