include_fields = {'bugs': [{'cf_has_str': '---',
   'cf_last_resolved': '2020-03-17T10:03:02Z',
   'op_sys': 'Unspecified',
   'cf_tracking_firefox112': '---',
   'blocks': [1619699],
   'cf_tracking_firefox111': '---',
   'duplicates': [],
   'cf_tracking_thunderbird_esr102': '---',
   'regressed_by': [],
   'mentors': [],
   'filed_via': 'standard_form',
   'cf_status_thunderbird_esr91': '---',
   'cf_crash_signature': '',
   'groups': [],
   'is_cc_accessible': True,
   'assigned_to_detail': {'nick': 'mhowell',
    'name': 'mhowell@mozilla.com',
    'id': 550257,
    'real_name': 'Molly Howell (she/her) [:mhowell]',
    'email': 'mhowell@mozilla.com'},
   'whiteboard': '',
   'mentors_detail': [],
   'component': 'Default Browser Agent',
   'priority': 'P1',
   'classification': 'Components',
   'id': 1602463,
   'cf_tracking_firefox113': '---',
   'alias': 'wdba-phase1',
   'cf_status_thunderbird_esr102': '---',
   'creation_time': '2019-12-09T14:57:48Z',
   'see_also': ['https://bugzilla.mozilla.org/show_bug.cgi?id=1619699',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1636539',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1682680',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1733984'],
   'cf_cab_review': '---',
   'dupe_of': None,
   'cc_detail': [{'real_name': 'Alicia Gray',
     'id': 590483,
     'email': 'agray@mozilla.com',
     'name': 'agray@mozilla.com',
     'nick': 'agray'},
    {'nick': 'bgrins',
     'name': 'bgrinstead@mozilla.com',
     'email': 'bgrinstead@mozilla.com',
     'id': 476442,
     'real_name': 'Brian Grinstead [:bgrins]'},
    {'email': 'bzhao@mozilla.com',
     'real_name': 'Hector Zhao [:hectorz]',
     'id': 424852,
     'name': 'bzhao@mozilla.com',
     'nick': 'hectorz'},
    {'email': 'catalin.sasca@softvision.com',
     'real_name': 'Catalin Sasca, QA [:csasca]',
     'id': 612754,
     'nick': 'csasca',
     'name': 'catalin.sasca@softvision.com'},
    {'email': 'chutten@mozilla.com',
     'id': 553004,
     'real_name': 'Chris H-C :chutten',
     'nick': 'chutten',
     'name': 'chutten@mozilla.com'},
    {'real_name': 'Emilio Cobos Álvarez (:emilio)',
     'id': 546716,
     'email': 'emilio@crisal.io',
     'name': 'emilio@crisal.io',
     'nick': 'emilio'},
    {'id': 632041,
     'real_name': 'Emily Thompson',
     'email': 'ethompson@mozilla.com',
     'nick': 'ethompson',
     'name': 'ethompson@mozilla.com'},
    {'name': 'jcristau@mozilla.com',
     'nick': 'jcristau',
     'email': 'jcristau@mozilla.com',
     'id': 580382,
     'real_name': 'Julien Cristau [:jcristau]'},
    {'id': 279663,
     'real_name': 'Jim Mathies [:jimm]',
     'email': 'jmathies@mozilla.com',
     'name': 'jmathies@mozilla.com',
     'nick': 'jimm'},
    {'nick': 'jwalker',
     'name': 'jwalker@mozilla.com',
     'id': 337891,
     'real_name': 'Joe Walker [:jwalker]',
     'email': 'jwalker@mozilla.com'},
    {'nick': 'mhowell',
     'name': 'mhowell@mozilla.com',
     'id': 550257,
     'real_name': 'Molly Howell (she/her) [:mhowell]',
     'email': 'mhowell@mozilla.com'},
    {'name': 'mihai.boldan@softvision.com',
     'nick': 'mboldan',
     'email': 'mihai.boldan@softvision.com',
     'real_name': 'Mihai Boldan, QA [:mboldan]',
     'id': 551058},
    {'name': 'nalexander@mozilla.com',
     'nick': 'nalexander',
     'email': 'nalexander@mozilla.com',
     'id': 432887,
     'real_name': 'Nick Alexander :nalexander [he/him]'},
    {'name': 'pdolanjski@mozilla.com',
     'nick': 'pdol',
     'email': 'pdolanjski@mozilla.com',
     'real_name': 'Peter Dolanjski [:pdol]',
     'id': 455532},
    {'name': 'rharter@mozilla.com',
     'nick': 'harter',
     'email': 'rharter@mozilla.com',
     'id': 575381,
     'real_name': 'Ryan Harter [:harter]'},
    {'nick': 'rachel',
     'name': 'tublitzed@gmail.com',
     'id': 646733,
     'real_name': 'Rachel Tublitz [:rachel]',
     'email': 'tublitzed@gmail.com'},
    {'nick': 'vlucaci',
     'name': 'vlad.lucaci@softvision.com',
     'email': 'vlad.lucaci@softvision.com',
     'id': 616533,
     'real_name': 'Vlad Lucaci, QA  (:vlucaci)'}],
   'is_confirmed': True,
   'cf_a11y_review_project_flag': '---',
   'cf_user_story': '',
   'creator': 'rtestard@mozilla.com',
   'cf_fx_iteration': '---',
   'product': 'Toolkit',
   'cf_status_firefox76': 'fixed',
   'cf_fx_points': '---',
   'cf_performance_impact': '---',
   'cf_status_firefox113': '---',
   'is_creator_accessible': True,
   'url': 'PRD: https://docs.google.com/document/d/1WWUGCSFv3ZclY8uJsqSYNSiX330ydQbyenlZy8gLB9U/edit#',
   'cf_status_firefox75': 'fixed',
   'resolution': 'FIXED',
   'platform': 'Unspecified',
   'cf_status_firefox112': '---',
   'last_change_time': '2022-06-01T17:27:48Z',
   'cf_rank': None,
   'version': 'unspecified',
   'cf_status_firefox_esr102': '---',
   'assigned_to': 'mhowell@mozilla.com',
   'comment_count': 36,
   'votes': 0,
   'cf_tracking_firefox_relnote': '75+',
   'cf_status_firefox111': '---',
   'is_open': False,
   'status': 'RESOLVED',
   'depends_on': [1621293, 1624047, 1624388, 1626020, 1630410, 1738211],
   'keywords': [],
   'severity': 'normal',
   'flags': [],
   'cc': ['agray@mozilla.com',
    'bgrinstead@mozilla.com',
    'bzhao@mozilla.com',
    'catalin.sasca@softvision.com',
    'chutten@mozilla.com',
    'emilio@crisal.io',
    'ethompson@mozilla.com',
    'jcristau@mozilla.com',
    'jmathies@mozilla.com',
    'jwalker@mozilla.com',
    'mhowell@mozilla.com',
    'mihai.boldan@softvision.com',
    'nalexander@mozilla.com',
    'pdolanjski@mozilla.com',
    'rharter@mozilla.com',
    'tublitzed@gmail.com',
    'vlad.lucaci@softvision.com'],
   'qa_contact': '',
   'summary': 'Windows Default Browser Agent - Phase 1',
   'type': 'enhancement',
   'regressions': [1628924],
   'target_milestone': 'mozilla76',
   'cf_qa_whiteboard': '',
   'cf_webcompat_priority': '---',
   'creator_detail': {'email': 'rtestard@mozilla.com',
    'id': 486264,
    'real_name': 'Romain Testard [:RT]',
    'nick': 'RT',
    'name': 'rtestard@mozilla.com'},
   'cf_tracking_thunderbird_esr91': '---',
   'cf_tracking_firefox_esr102': '---'},
  {'blocks': [],
   'cf_tracking_firefox112': '---',
   'cf_tracking_firefox111': '---',
   'cf_tracking_thunderbird_esr102': '---',
   'regressed_by': [],
   'duplicates': [],
   'cf_last_resolved': '2020-09-11T16:20:14Z',
   'cf_has_str': '---',
   'op_sys': 'Unspecified',
   'filed_via': 'standard_form',
   'mentors': [],
   'cf_crash_signature': '',
   'cf_status_thunderbird_esr91': '---',
   'groups': [],
   'component': 'Default Browser Agent',
   'mentors_detail': [],
   'is_cc_accessible': True,
   'assigned_to_detail': {'name': 'bytesized@mozilla.com',
    'nick': 'bytesized',
    'email': 'bytesized@mozilla.com',
    'real_name': 'Robin Steuber (they/them) [:bytesized]',
    'id': 563604},
   'whiteboard': '',
   'cf_tracking_firefox113': '---',
   'cf_status_thunderbird_esr102': '---',
   'alias': 'wdba-phase2',
   'cf_cab_review': '---',
   'creation_time': '2020-03-03T18:14:25Z',
   'see_also': ['https://bugzilla.mozilla.org/show_bug.cgi?id=1602463',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1635507',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1657158',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1664510',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1682680',
    'https://bugzilla.mozilla.org/show_bug.cgi?id=1684971'],
   'priority': 'P1',
   'classification': 'Components',
   'id': 1619699,
   'cf_user_story': '',
   'cf_a11y_review_project_flag': '---',
   'is_confirmed': True,
   'cf_fx_iteration': '---',
   'creator': 'tublitzed@gmail.com',
   'product': 'Toolkit',
   'dupe_of': None,
   'cc_detail': [{'id': 454100,
     'real_name': '(No longer employed by Mozilla) Aaron Klotz',
     'email': 'bugzilla@dblohm7.ca',
     'name': 'bugzilla@dblohm7.ca',
     'nick': 'bugzilla'},
    {'name': 'chutten@mozilla.com',
     'nick': 'chutten',
     'email': 'chutten@mozilla.com',
     'id': 553004,
     'real_name': 'Chris H-C :chutten'},
    {'email': 'jvehent@mozilla.com',
     'id': 469465,
     'real_name': 'Julien Vehent',
     'nick': 'jvehent',
     'name': 'jvehent@mozilla.com'},
    {'real_name': 'Axel Hecht [:Pike]',
     'id': 215498,
     'email': 'l10n@mozilla.com',
     'name': 'l10n@mozilla.com',
     'nick': 'Pike'},
    {'id': 609516,
     'real_name': 'Michael Droettboom [:mdroettboom]',
     'email': 'mdroettboom@mozilla.com',
     'nick': 'mdroettboom',
     'name': 'mdroettboom@mozilla.com'},
    {'name': 'mhowell@mozilla.com',
     'nick': 'mhowell',
     'email': 'mhowell@mozilla.com',
     'real_name': 'Molly Howell (she/her) [:mhowell]',
     'id': 550257},
    {'real_name': 'Mark Reid [:mreid]',
     'id': 421860,
     'email': 'mreid@mozilla.com',
     'name': 'mreid@mozilla.com',
     'nick': 'mreid'},
    {'name': 'nalexander@mozilla.com',
     'nick': 'nalexander',
     'email': 'nalexander@mozilla.com',
     'real_name': 'Nick Alexander :nalexander [he/him]',
     'id': 432887},
    {'email': 'rharter@mozilla.com',
     'id': 575381,
     'real_name': 'Ryan Harter [:harter]',
     'nick': 'harter',
     'name': 'rharter@mozilla.com'},
    {'name': 'rtanglao@mozilla.com',
     'nick': 'rolandtanglao',
     'email': 'rtanglao@mozilla.com',
     'id': 352356,
     'real_name': 'Roland Tanglao needinfo please :rolandtanglao, :mohnkuchen, :adobo, :sinigang, :roland'},
    {'name': 'rtestard@mozilla.com',
     'nick': 'RT',
     'real_name': 'Romain Testard [:RT]',
     'id': 486264,
     'email': 'rtestard@mozilla.com'}],
   'resolution': 'FIXED',
   'platform': 'Unspecified',
   'cf_status_firefox112': '---',
   'last_change_time': '2022-06-01T17:33:36Z',
   'cf_fx_points': '---',
   'cf_performance_impact': '---',
   'url': 'https://docs.google.com/document/d/1WWUGCSFv3ZclY8uJsqSYNSiX330ydQbyenlZy8gLB9U/edit#',
   'is_creator_accessible': True,
   'cf_status_firefox113': '---',
   'comment_count': 14,
   'cf_tracking_firefox_relnote': '---',
   'votes': 0,
   'cf_status_firefox111': '---',
   'cf_rank': None,
   'version': 'unspecified',
   'cf_status_firefox_esr102': '---',
   'assigned_to': 'bytesized@mozilla.com',
   'regressions': [],
   'cf_qa_whiteboard': '',
   'target_milestone': '---',
   'cf_webcompat_priority': '---',
   'cf_tracking_thunderbird_esr91': '---',
   'cf_tracking_firefox_esr102': '---',
   'creator_detail': {'email': 'tublitzed@gmail.com',
    'real_name': 'Rachel Tublitz [:rachel]',
    'id': 646733,
    'nick': 'rachel',
    'name': 'tublitzed@gmail.com'},
   'is_open': False,
   'depends_on': [1602463, 1621703, 1636539, 1657147, 1657170, 1660920],
   'status': 'RESOLVED',
   'flags': [],
   'severity': 'normal',
   'keywords': [],
   'summary': 'Windows Default Browser Agent - Phase 2 - Notifications',
   'qa_contact': '',
   'type': 'task',
   'cc': ['bugzilla@dblohm7.ca',
    'chutten@mozilla.com',
    'jvehent@mozilla.com',
    'l10n@mozilla.com',
    'mdroettboom@mozilla.com',
    'mhowell@mozilla.com',
    'mreid@mozilla.com',
    'nalexander@mozilla.com',
    'rharter@mozilla.com',
    'rtanglao@mozilla.com',
    'rtestard@mozilla.com']}]}

comments = {'comments': {},
 'bugs': {'1619699': {'comments': [{'count': 0,
     'text': "As a follow up to the first step in the WDBA project, we'll be implementing notifications for Win 10 users who have switched their default browser from Firefox to Edge.\n\n### Requirements\n\n* Follows designs specified [here](https://mozilla.invisionapp.com/share/ZYW3NMHJG69#/screens/406213035_Windows_Notifications), which were created from [1607833](https://bugzilla.mozilla.org/show_bug.cgi?id=1607833).\n* Implements notifications following [MSFT's toast notification guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts).\n* Notifications are displayed following this logic:\n      - [first notification] If we detect that a user’s previous default was Firefox, and now it’s Edge, we show the first notification. If this has been shown once, never show it again.\n      - [second notification] If the user clicked “remind me later” in the first notification, we’ll show the second notification after 7 days. We’ll only show this notification if the users’ default is Edge. If this has been shown once, never show it again.\n* Includes telemetry, specifically:\n  1. which notification is shown (we have two)\n  2.  which action was taken (clicked primary button, clicked secondary button, clicked dismiss icon)",
     'creation_time': '2020-03-03T18:14:25Z',
     'id': 14674405},
    {'id': 14700362,
     'count': 1,
     'text': ":mreid - We met yesterday with Ryan Harter from Data Science about using either a document id, or a client id that's separate from the actual profile's client id. The concern here is that we may not be able to de-dupe clients who send a lot of pings. Do you think this is something that we should try to address for this phase of this project?",
     'creation_time': '2020-03-17T13:52:43Z'},
    {'id': 14719698,
     'creation_time': '2020-03-27T13:12:03Z',
     'text': "From bug 1621703, it sounds like the instrumentation will be done using Glean, so I'll redirect to Mike on whether we need to do anything novel for handling duplicate submissions.",
     'count': 2},
    {'count': 3,
     'text': "*If* using Glean (keeping in mind that Glean in Windows won't be available until at least 2021Q1), this wouldn't be a problem to generate client ids that are different from the standard client id and use that for deduplication for each client.\n\nI doubt it would be a problem even if using the existing legacy telemetry system, but I think :chutten could better speak to that.",
     'creation_time': '2020-03-27T16:16:45Z',
     'id': 14720103},
    {'creation_time': '2020-03-27T17:07:17Z',
     'text': "(In reply to Michael Droettboom [:mdroettboom] from comment #3)\n> *If* using Glean (keeping in mind that Glean in Windows won't be available until at least 2021Q1)\n\nAh, very good to know. That would mean that we won't be using it here, since we're planning to ship this in Q2 2020.",
     'count': 4,
     'id': 14720198},
    {'count': 5,
     'text': "From the sounds of things none of Telemetry's docid or client_id machinery is likely to be available to the agent since it's outside of Firefox. We could do what we're doing for the dataupload pref (throw it over the wall using the registry)  but that only gets you the client_id that was most recently used in the most recently-used Firefox profile, not anything that'll clue you in to resets, deletion-requests, or how to generate your own.\n\nA mechanism for weighting and identifying chatty vs quiet clients seems like a good thing to have. I recommend having your own identifier that rotates regularly (maybe every 28 days/pings?) coupled with a sequence number.",
     'creation_time': '2020-03-27T17:18:54Z',
     'id': 14720225},
    {'id': 14815279,
     'count': 6,
     'text': "Based on the lack of API support, we're removing l10n from the initial release here and will be showing the notification for users with both a system and browser local of English only.",
     'creation_time': '2020-05-12T19:52:08Z'},
    {'id': 14815310,
     'count': 7,
     'text': "@Pike - I'm not sure how I ought to limit to English Firefox and how to prevent localizers from making unnecessary translations. Could you point me in the right direction here? I'd like to leave in as much of the l10n handling as possible to make it easy to flip on if we solve the necessary problems.",
     'creation_time': '2020-05-12T20:04:45Z'},
    {'creation_time': '2020-05-13T11:34:52Z',
     'text': "I guess the right way to do this would be to put the ini file outside of `locales/en-US`, and to move the build logic away from `toolkit/locales/moz.build` and `LOCALIZED_GENERATED_FILES` to something and `GENERATED_FILES`.\n\nI'd also like to get a better understanding of the role of toolkit and browser here, and platforms, so that might be also good to do in a follow-up.\n\nShould we re-use bug 1621700 for that at a later point? Probably regardless of the Fluent conversation in that bug.",
     'count': 8,
     'id': 14816454},
    {'id': 14817127,
     'count': 9,
     'text': "@Pike - That sounds like a good solution for preventing unnecessary translations but, unless I'm mistaken, it will not limit execution to English Firefox; everyone would just see English text, regardless of their locale. Is there a good way of addressing that issue?\n\nI'm not sure what you are asking about toolkit, browser, and platforms. Perhaps you could rephrase the question?",
     'creation_time': '2020-05-13T16:37:22Z'},
    {'id': 14817229,
     'text': "Oh, I thought you had that figured out, misread your comment. Really depends on how you start your feature. There's nothing on the packaging side, I think.\n\nIf you can get to the locale service, relatively late, and check https://searchfox.org/mozilla-central/source/intl/locale/mozILocaleService.idl#145 to be `en-US`, you can enable your feature. Caveat, during startup, Firefox might go through a phase with `en-US`, and then reconsider, for example when language packs kick in. https://firefox-source-docs.mozilla.org/intl/locale_startup.html has details.\n\nRe browser/toolkit: Thunderbird and SeaMonkey both go through `toolkit/locales/moz.build`. So if you put the `LOCALIZED_GENERATED_FILES` in toolkit, they will create those files. They might not package them, but still.\n\nRe platforms, I'd like to make sure that as much of the l10n repacks is platform agnostic, and that platform dependencies kick in in packaging, if at all. That'll allow for some cost-cutting optimizations in the repack automation.",
     'creation_time': '2020-05-13T17:12:56Z',
     'count': 10},
    {'id': 14817273,
     'text': "I don't think I can get the locale service outside of Firefox. Any other options?\n\nI think reusing bug 1621700 for the browser/toolkit/platforms changes sounds fine.",
     'creation_time': '2020-05-13T17:31:49Z',
     'count': 11},
    {'count': 12,
     'creation_time': '2020-05-13T17:48:40Z',
     'text': 'Discussed on Slack.',
     'id': 14817331},
    {'count': 13,
     'text': 'This feature is no longer confidential.',
     'creation_time': '2020-08-07T21:48:59Z',
     'id': 14978879}]},
  '1602463': {'comments': [{'text': 'Context:\n- The new Chromium Edge is set to be released on January 15th 2020\n- The last Windows 7 security update will happen on January 14th 2020\n- We fear that Microsoft will aggressively promote Chromium Edge when it releases and we want to be able to detect trend shifts in Win10 and Win7 default browsers so we’re armed to react to forced changes on browser default\n\nWhat is necessary:\n- An “always on” agent on Windows that allows:\n--- Collecting data on default browser set\n--- Re-engaging Firefox users through OS notifications based on a set of events. Events would initially include a change in system settings from a Firefox default browser to an Edge default browser but should be extensible to allow driving engagement for other purposes.\n\nAcceptance criteria:\nP1 - Win10 support: Installing Firefox will install the agent, uninstalling Firefox will uninstall the agent, updating Firefox will install the agent.\nP1 - The agent runs well in environments where anti-virus software is installed\nP1 - The agent launches as Windows starts\nP1 - The agent can be disabled for managed deployments\nP1 - The agent sends a daily ping with information about the default browser on the system\nP2 - Win7 support: Installing Firefox will install the agent, uninstalling Firefox will uninstall the agent, updating Firefox will install the agent.\nP2 - The agent delivers a system notification to the Windows 10 action center if the default browser on the system changed from Firefox to Edge  \nP2 - The agent auto launch on startup behavior is controlled by a Firefox preference to allow A/B testing through Experimenter\nP2 - Telemetry allows identifying browser sessions that start by opening Firefox through a notification\nP3 - The agent delivers a system notification on Windows 7 if the default browser on the system changed from Firefox to Edge',
     'creation_time': '2019-12-09T14:57:48Z',
     'count': 0,
     'id': 14535990},
    {'count': 1,
     'text': "Open question - Microsoft currently promotes Edge heavily through notifications. They also question user default browser changes through notifications. I'm curious why Product feels Microsoft's behavior will become more aggressive than it already is? Also I don't understand why we think users will switch to Chromium Edge by large numbers (Is there some way we can research this?), it's really just a new shell on top of Chrome.\n\nI like the idea of countering Microsoft's default browser promoting but I fail to see why this project is critically tied to the release of Chromium Edge. I'd also like point out the timelines published for this aren't realistic so hopefully I'm right about this.",
     'creation_time': '2019-12-09T20:43:07Z',
     'id': 14536987},
    {'count': 2,
     'text': '(In reply to Jim Mathies [:jimm] from comment #1)\n> Open question - Microsoft currently promotes Edge heavily through notifications. They also question user default browser changes through notifications. I\'m curious why Product feels Microsoft\'s behavior will become more aggressive than it already is? Also I don\'t understand why we think users will switch to Chromium Edge by large numbers (Is there some way we can research this?), it\'s really just a new shell on top of Chrome.\n\nWe saw Microsoft switch defaults on users previously with OS updates, via Win10 updates (beyond the notifications they do). They have a large investment tied to this revamp and they will want to maximize success, so their incentives will be to push it in whatever ways they can so they can prove to their leadership and shareholders that this was the right strategy.\n\nWe\'ve done an initial user study [1]: that concluded: "Respondents think positively of the new Edge compared to other browsers as well as the previous version of Edge. Compared to other browsers and the previous of Edge, the respondents think the new Edge has more features, is more stable, is faster, is safer, works well with more websites, and is better for privacy. "\n\nThese two reasons make it potentially a larger threat. dd\n\n> I\'d also like point out the timelines published for this aren\'t realistic so hopefully I\'m right about this.\n\nWe\'re happy to work with you on what is realistic. Even if we\'re not ready on day 1, better late than never.\n\n[1] https://docs.google.com/document/d/1ufLIZDoUlSLyNB0q05UNvaBhyfScd9al2UXB1KeNYLU/edit?ts=5de090ec',
     'creation_time': '2019-12-11T20:53:44Z',
     'id': 14541709},
    {'creation_time': '2020-02-06T19:31:54Z',
     'text': 'Created attachment 9124827\nBug 1602463 Part 1 - Add a build flag to disable the default browser agent. r=agashlin,bytesized,nalexander',
     'count': 3,
     'id': 14627180},
    {'id': 14627185,
     'count': 4,
     'creation_time': '2020-02-06T19:33:56Z',
     'text': 'Created attachment 9124828\nBug 1602463 Part 3 - Windows default browser agent. r=agashlin,bytesized,nalexander\n\n\n\nDepends on D61888'},
    {'id': 14627190,
     'count': 5,
     'text': 'Created attachment 9124830\nBug 1602463 Part 4 - Register/unregister the default browser agent scheduled task during install/uninstall. r=agashlin,bytesized,nalexander\n\n\n\nDepends on D61889',
     'creation_time': '2020-02-06T19:36:14Z'},
    {'id': 14627203,
     'creation_time': '2020-02-06T19:38:47Z',
     'text': 'Created attachment 9124831\nBug 1602463 Part 2 - Add a pref to enable/disable the default browser agent and reflect it to the registry where the agent can read it. r=agashlin,bytesized,nalexander\n\n\n\nDepends on D61891',
     'count': 6},
    {'id': 14627550,
     'creation_time': '2020-02-06T22:04:14Z',
     'text': 'Hi! A drive-by reminder that new data collections are subject to [Data Collection Review](https://wiki.mozilla.org/Firefox/Data_Collection) (and the data review must be made publicly accessible to all those subject to the collection).\n\n(( If you were already planning on requesting data review, Good Work and sorry for the noise ))',
     'count': 7},
    {'id': 14627553,
     'count': 8,
     'text': "I'm filling out the form right now. ;)",
     'creation_time': '2020-02-06T22:05:05Z'},
    {'id': 14627631,
     'text': 'Comment on attachment 9124828\nBug 1602463 Part 3 - Windows default browser agent. r=agashlin,bytesized,nalexander\n\n> What questions will you answer with this data?\n\nComment 0 and the linked PRD [1] explain this, but the specific idea is to monitor for changes in default browser settings on Windows resulting from the Chrome-based Edge rollout.\n\n> Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?\n\nWe need to determine whether an operating system change has an effect on user behavior, to know if we need to take specific steps to counteract it. We still don\'t know the full details on how the rollout/migration for the new Edge will be implemented or what effects on the default browser setting might result.\n\n> What alternative methods did you consider to answer these questions? Why were they not sufficient?\n\nThere\'s not really any existing Firefox telemetry that will work, for the basic reason that it all requires running Firefox, and the scenario we\'re worried about is one in which the default browser has been changed and therefore Firefox no longer runs.\n\n> Can current instrumentation answer these questions?\n\nSee above.\n\n> List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.\n\nCategory 1:\n* Firefox release channel\n* Firefox version\n* Operating system (Windows) version\n* Operating system locale setting\n\nCategory 2 (I\'m not 100% confident in this category assignment):\n* Current system default browser, represented as one of the strings "firefox", "chrome", "edge", "edge-chrome", "ie", "opera", or "brave".\n* Previous system default browser, before it was changed to the current one; one of the same set of strings as above.\n\nThere\'s ping documentation included in this patch which provides more details.\n\n> How long will this data be collected?\n\nPermanently as far as I know (with me, mhowell, as the responsible engineer), but product may have a timeframe in mind that I\'m unaware of.\n\n> What populations will you measure?\n\nAll Windows users (other operating systems are excluded).\n\n> Which release channels?\n\nAll.\n\n> Which countries?\n\nAll.\n\n> Which locales?\n\nAll.\n\n> Any other filters? Please describe in detail below.\n\nNone at this time.\n\n> If this data collection is default on, what is the opt-out mechanism for users?\n\nThe normal Firefox telemetry opt-out pref is honored, and this patch series adds a new pref `defaultagent.enabled` which specifically disables the agent\'s functionality. The telemetry opt-out enterprise policy is also honored, and a new agent-specific policy is added here as well; these policies allow opting out before it is possible that any pings would have been generated.\n\n> Please provide a general description of how you will analyze this data.\n\nI\'m not going to be doing this analysis myself so I can\'t be certain (contact Romain Testard for details), but I believe the analysis would be conducted mostly (and perhaps entirely) via STMO queries on these pings (which are custom pings without any telemetry identifiers).\n\n> Where do you intend to share the results of your analysis?\n\nI think the results would not be widely shared (i.e., the STMO queries would be accessible, but nothing broadly distributed otherwise). But again, ask Romain for details.\n\n> Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?\n\nNo.\n\n> Are you using that on the Mozilla backend? Or going directly to the third-party?\n\nThe Mozilla backend.\n\n\n[1] Note that the notification functionality described in the PRD has not been implemented yet.',
     'creation_time': '2020-02-06T22:40:30Z',
     'count': 9},
    {'creation_time': '2020-02-06T23:29:23Z',
     'text': "I've opened https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/495 for the schema for the newly added ping.",
     'count': 10,
     'id': 14627682},
    {'id': 14628828,
     'count': 11,
     'creation_time': '2020-02-07T16:33:43Z',
     'text': "Comment on attachment 9124828\nBug 1602463 Part 3 - Windows default browser agent. r=agashlin,bytesized,nalexander\n\nSome notes:\n\n1. Please file future data review requests as attachments on bugs. This fits better into Data Stewardship's workflow (and keeps the comments timeline cleaner)\n2. The review request seems complete and correct, though I worry that the agent might perhaps send data before the user has had a chance to review the Privacy Notice and take action to opt out. This might fall outside the scope of data review, so I apologize if I overstep, but has Legal/Trust been involved in the consent model design?\n3. Will this bug be made public when the data collection begins? By policy, Data Reviews must be available to the population affected by the collection. (Usually in these cases where you want some discussion/design to remain private a bug just for the data review is filed and is either public or is confidential until it's merged and then is made public)"},
    {'text': "(In reply to Chris H-C :chutten from comment #11)\n> 1. Please file future data review requests as attachments on bugs. This fits better into Data Stewardship's workflow (and keeps the comments timeline cleaner)\n\nSorry about that. To clarify, does that mean that the recommended procedure is to fill out the form in a text file (or I guess a Markdown file, but there's disagreement in different docs about that), attach that to the bug, and then set the request flag on that attachment? I sure wouldn't mind if some piece of documentation were a little more explicit about that, since it sounds like a pretty unique flow for Bugzilla and I obviously assumed it worked like how other request flags work.\n\n> 2. The review request seems complete and correct, though I worry that the agent might perhaps send data before the user has had a chance to review the Privacy Notice and take action to opt out. This might fall outside the scope of data review, so I apologize if I overstep, but has Legal/Trust been involved in the consent model design?\n\nThe task runs on a 24-hour schedule that starts counting from the time of installation, so nothing is sent for 24 hours after then; I was hoping that would be enough delay. I certainly don't mind consulting legal and/or trust though if you feel like we should.\n\n> 3. Will this bug be made public when the data collection begins? By policy, Data Reviews must be available to the population affected by the collection. (Usually in these cases where you want some discussion/design to remain private a bug just for the data review is filed and is either public or is confidential until it's merged and then is made public)\n\nRedirecting this question to Romain because I'm honestly not certain why this bug was filed as private in the first place.",
     'creation_time': '2020-02-07T17:09:56Z',
     'count': 12,
     'id': 14628897},
    {'id': 14628934,
     'count': 13,
     'creation_time': '2020-02-07T17:30:23Z',
     'text': '(In reply to Molly Howell (she/her) [:mhowell] from comment #12)\n> (In reply to Chris H-C :chutten from comment #11)\n> > 1. Please file future data review requests as attachments on bugs. This fits better into Data Stewardship\'s workflow (and keeps the comments timeline cleaner)\n> \n> Sorry about that. To clarify, does that mean that the recommended procedure is to fill out the form in a text file (or I guess a Markdown file, but there\'s disagreement in different docs about that), attach that to the bug, and then set the request flag on that attachment? I sure wouldn\'t mind if some piece of documentation were a little more explicit about that, since it sounds like a pretty unique flow for Bugzilla and I obviously assumed it worked like how other request flags work.\n\nNo worries, the work is imperfect and we try to make it better each day. You can straight up paste the text of the review request into the "Add Attachment" BMO UI and it\'ll take care of making it into a file for you. The documentation covering how data reviews are requested can be found on wikimo: https://wiki.mozilla.org/Firefox/Data_Collection#Requesting_Data_Collection\n\nHappy to help out with clarifying that page to make it better. Ideally, Data Stewardship would get some budget to get a web service set up so that the reviews could be, y\'know, real forms. And a database so we could audit things more easily and so users could query things more easily and so we could interoperate with other data tools.\n\nAlas : |\n \n> > 2. The review request seems complete and correct, though I worry that the agent might perhaps send data before the user has had a chance to review the Privacy Notice and take action to opt out. This might fall outside the scope of data review, so I apologize if I overstep, but has Legal/Trust been involved in the consent model design?\n> \n> The task runs on a 24-hour schedule that starts counting from the time of installation, so nothing is sent for 24 hours after then; I was hoping that would be enough delay. I certainly don\'t mind consulting legal and/or trust though if you feel like we should.\n\nIf there were a signal that Firefox were run in the first 23h30m of being installed there\'d be no worries at all with this schedule as that puts it in line with the existing data reporting policy code inside Firefox (ie, give 30min to read the notice and find the setting). Since this is decoupled from Firefox running, I don\'t know if the same thing applies. I say reach out to Alicia Gray about this requirement.'},
    {'id': 14665401,
     'count': 14,
     'creation_time': '2020-02-27T17:03:08Z',
     'text': "Quick update on the current status here: the patch stack for this bug is complete, and landing it is blocked on bug 1615281, which is going to be a public blog post explaining how the data collection for this thing works and what the methods for opting out of it will be. Nothing will be pushed even to Nightly until that blog post is up, so that we don't start doing any collection before there's clear information on how to turn it off."},
    {'count': 15,
     'text': "(In reply to Molly Howell (she/her) [:mhowell] from comment #14)\n> Quick update on the current status here: the patch stack for this bug is complete [...]\n\nGot ahead of myself: it turned out that we need some stubs in the Firefox policy engine for the default agent policy even though the engine doesn't do anything to implement it, so that it shows up properly in about:policies. So I'm adding another patch to the series to address that.",
     'creation_time': '2020-03-02T17:53:54Z',
     'id': 14671930},
    {'text': 'Created attachment 9130218\nBug 1602463 Part 5 - Add policy engine support for the default browser agent policy. r=mkaply\n\n\n\nDepends on D61891',
     'creation_time': '2020-03-02T18:49:10Z',
     'count': 16,
     'id': 14672102},
    {'count': 17,
     'text': "Adjusting this issue so it's clear this work pertains to the following only:\n\n* Win10+7 support: Installing Firefox will install the agent, uninstalling Firefox will uninstall the agent, updating Firefox will install the agent.\n* The agent runs well in environments where anti-virus software is installed.\n* The agent launches as Windows starts.\n* The agent can be disabled for managed deployments.\n* The agent sends a daily ping with information about the default browser on the system.\n\nWe'll file future follow up issues to track work on the next steps of this project.",
     'creation_time': '2020-03-03T18:10:27Z',
     'id': 14674390},
    {'count': 18,
     'text': "chutten: can you confirm data review approval for this (pending us reaching out to Alicia Gray)?\n\nagray: can you confirm that we did indeed connect with you (was done via email) and that we're moving forward with a plan to first publish a [blog post](https://bugzilla.mozilla.org/show_bug.cgi?id=1615281) here?\n\nI'm trying to get all our approvals rounded up in one place so we can move forward with a request for uplift into 75.",
     'creation_time': '2020-03-09T20:57:51Z',
     'id': 14685498},
    {'creation_time': '2020-03-09T23:28:15Z',
     'text': 'HI Rachel,\n\nYes, confirming review was completed with Trust and approval given for this.  Blog was also reviewed and commented on.  No blockers on the Trust side.  My review notes were as follows:\n\nThank you for your email - more than happy to give input for you on this question. I’ve listed out the points below that will answer your question and give some additional context for handling perceived risk.\n\nThe data collection outside of Firefox is ok if:\n-it is consistent with the data categories collection (which it is)\n-it honors the opt-out setting (which it looks like it can/will)\n-we are transparent about it.  The real risk here is in violating our “no surprises” principle.  People might be surprised by this so the team needs to think about and plan for how we can be transparent about it. I’d be happy to help support the development of a comms plan, but this needs to be part of the equation.\n\nRe: 24 hour installation v. launch issue, this would be ok with us.  If the user hasn’t changed their telemetry opt-out pref by then for whatever r\nreason, we’re fine accepting it as default collection. \n\nCollection time frame:  it’s my understanding the request to collect is on-going (permanent ping).  We’d recommend limiting this collection to 1 year and then reassessing its usefulness. You can always extend the collection if it is useful and make it permanent.\n\nSecondary use cases:  The PRD mentions use cases that could leverage this data for notifications to users for a couple of different purposes.  Please note that any use of this data beyond the measurement itself (e.g. marketing or in-product notifications etc.) would need a different review through Trust and Legal.  Approval for the data collection doesn’t give approval for the other potential use cases.',
     'count': 19,
     'id': 14685809},
    {'id': 14686640,
     'count': 20,
     'creation_time': '2020-03-10T13:44:34Z',
     'text': "I think we should still perform a data review in public for the collection. This will ensure we have things like public-facing documentation for the data being collected, and a public process we've completed and can point to in order to show that this is all above board. This can be in a separate bug to maintain this as a confidential one."},
    {'id': 14686709,
     'count': 21,
     'creation_time': '2020-03-10T14:12:42Z',
     'text': "(In reply to Chris H-C :chutten from comment #20)\n> I think we should still perform a data review in public for the collection. This will ensure we have things like public-facing documentation for the data being collected, and a public process we've completed and can point to in order to show that this is all above board. This can be in a separate bug to maintain this as a confidential one.\n\nThanks, Chris. Just filed [this request](https://bugzilla.mozilla.org/show_bug.cgi?id=1621293) as a public bug."},
    {'text': 'Backed out 5 changesets for causing diffoscope failures.\n\nBackout link: https://hg.mozilla.org/integration/autoland/rev/e87acf21935d5ff91c3e9dafe554a314ad31fd2b\n\nPush with failures: https://treeherder.mozilla.org/#/jobs?repo=autoland&tochange=e87acf21935d5ff91c3e9dafe554a314ad31fd2b&fromchange=911385b3cbc028a6b86ab884ca7955b4aaaa9898&searchStr=diffoscope%2Copt%2Cdiff-artifact-win64-aarch64-eme-validation%2C%28dwe%29&selectedJob=293363887\n\nFailure log: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=293366507&repo=autoland&lineNumber=7026',
     'creation_time': '2020-03-16T19:24:00Z',
     'count': 22,
     'id': 14698999},
    {'id': 14699001,
     'creation_time': '2020-03-16T19:24:37Z',
     'text': 'Working on it.',
     'count': 23},
    {'creation_time': '2020-03-16T20:13:12Z',
     'text': 'Found a fix that makes the failing job pass [on try](https://treeherder.mozilla.org/#/jobs?repo=try&revision=f1330ff13699e2bfdb8023bbf2ace53737ee4270&selectedJob=293386300), about to try landing again with that.',
     'count': 24,
     'id': 14699074},
    {'count': 25,
     'text': "I'm also seeing these failures: https://treeherder.mozilla.org/#/jobs?repo=autoland&searchStr=linux%2C18.04%2Cx64%2Cshippable%2Copt%2Cmochitests%2Ctest-linux1804-64-shippable%2Fopt-mochitest-browser-chrome-e10s-4%2Cm%28bc4%29&tochange=e87acf21935d5ff91c3e9dafe554a314ad31fd2b&fromchange=9f58bd341b2f53ac6f692586991a2659240d0a0c&selectedJob=293371201",
     'creation_time': '2020-03-16T20:16:48Z',
     'id': 14699078},
    {'id': 14699079,
     'count': 26,
     'text': "Thanks, didn't see that; will add in that fix also.",
     'creation_time': '2020-03-16T20:18:03Z'},
    {'count': 27,
     'creation_time': '2020-03-16T22:29:27Z',
     'text': "(In reply to Alexandru Michis [:malexandru] from comment #22)\n> Backed out 5 changesets for causing diffoscope failures.\n> \n> Backout link: https://hg.mozilla.org/integration/autoland/rev/e87acf21935d5ff91c3e9dafe554a314ad31fd2b\n> \n> Push with failures: https://treeherder.mozilla.org/#/jobs?repo=autoland&tochange=e87acf21935d5ff91c3e9dafe554a314ad31fd2b&fromchange=911385b3cbc028a6b86ab884ca7955b4aaaa9898&searchStr=diffoscope%2Copt%2Cdiff-artifact-win64-aarch64-eme-validation%2C%28dwe%29&selectedJob=293363887\n> \n> Failure log: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=293366507&repo=autoland&lineNumber=7026\n\nIt surprises me that that diffoscope failures are causing backouts at all; that's new since I looked last.  NI to me to follow-up at a time when I can think about this.",
     'id': 14699328},
    {'id': 14700024,
     'creation_time': '2020-03-17T10:03:02Z',
     'text': 'https://hg.mozilla.org/integration/autoland/rev/c717a1a030e244dfa41e60277a485dabe7483294\nhttps://hg.mozilla.org/integration/autoland/rev/54c091d1c59c3efd0b54a5d6acf84d0c12f381ee\nhttps://hg.mozilla.org/integration/autoland/rev/91b694e8361543ba446e84962f8d42d2868f2b5c\nhttps://hg.mozilla.org/integration/autoland/rev/61e1afdf2642321ffb5fa73e2e6f4fa433385eb1\nhttps://hg.mozilla.org/integration/autoland/rev/952bdf4adda8b871237f0c917e5976c22b7b9c3c\nhttps://hg.mozilla.org/mozilla-central/rev/c717a1a030e2\nhttps://hg.mozilla.org/mozilla-central/rev/54c091d1c59c\nhttps://hg.mozilla.org/mozilla-central/rev/91b694e83615\nhttps://hg.mozilla.org/mozilla-central/rev/61e1afdf2642\nhttps://hg.mozilla.org/mozilla-central/rev/952bdf4adda8',
     'count': 28},
    {'id': 14700342,
     'creation_time': '2020-03-17T13:45:40Z',
     'text': "Comment on attachment 9124827\nBug 1602463 Part 1 - Add a build flag to disable the default browser agent. r=agashlin,bytesized,nalexander\n\n### Beta/Release Uplift Approval Request\n* **User impact if declined**: There is no direct user impact here; it’s background telemetry that we’re collecting. However, if declined, we risk losing out on collecting potentially valuable data that’s time sensitive due to the recent Edgium release.\n* **Is this code covered by automated tests?**: No\n* **Has the fix been verified in Nightly?**: No\n* **Needs manual test from QE?**: No\n* **If yes, steps to reproduce**: \n* **List of other uplifts needed**: None\n* **Risk to taking this patch**: Low\n* **Why is the change risky/not risky? (and alternatives if risky)**: Low: It’s a scheduled task that’s run in the background; not user facing.\nIt is however worth noting that there are some PR concerns related to this release due to the additional background telemetry that we’re collecting. To mitigate these risks, we've published a blog post here: https://blog.mozilla.org/data/2020/03/16/understanding-default-browser-trends/ that we plan to point users to.\n* **String changes made/needed**: Yes, [here, in the last patch](https://phabricator.services.mozilla.com/D64992) related to enterprise policies. See Molly's comment below here (comment #30).",
     'count': 29},
    {'count': 30,
     'text': "There actually is a new string in the part 5 patch here. I should have recognized earlier that that would complicate uplift, I apologize for not thinking of it.\n\nIf it's a problem, my proposed workaround would be to leave part 5 out of the uplift. The only function of that part is to add documentation in about:policies for the enterprise policy that the rest of the series implements, and to prevent the new policy from appearing there as an error. In my opinion it would be okay to knowingly leave those issues in place for a single version, if it is necessary.",
     'creation_time': '2020-03-17T14:46:58Z',
     'id': 14700456},
    {'id': 14714296,
     'text': 'Since the uplift request here was filed, bug 1624047 and bug 1624388 have been added to the "other uplifts needed" list. My apologies.',
     'creation_time': '2020-03-24T20:49:23Z',
     'count': 31},
    {'id': 14715952,
     'creation_time': '2020-03-25T18:07:04Z',
     'text': 'Comment on attachment 9124827\nBug 1602463 Part 1 - Add a build flag to disable the default browser agent. r=agashlin,bytesized,nalexander\n\napproved for 75.0b9 per Selena.',
     'count': 32},
    {'id': 14716983,
     'text': 'https://hg.mozilla.org/releases/mozilla-beta/rev/272ce48e4c439035269d4e801a3e78ef3d0805e9\nhttps://hg.mozilla.org/releases/mozilla-beta/rev/53fd3c5b278d0d3e8728952b9f29c8e8cba22e92\nhttps://hg.mozilla.org/releases/mozilla-beta/rev/33c21237c0153b080d372eeb4334771131c7baa3\nhttps://hg.mozilla.org/releases/mozilla-beta/rev/cff6f339d416472248b2f346a11c57413ad6a8f4\nhttps://hg.mozilla.org/releases/mozilla-beta/rev/3be328e257eb8d588d8887e22e548763a91b4a63',
     'creation_time': '2020-03-26T08:55:30Z',
     'count': 33},
    {'creation_time': '2020-07-06T16:26:08Z',
     'text': "> It surprises me that that diffoscope failures are causing backouts at all; that's new since I looked last.  NI to me to follow-up at a time when I can think about this.\n\nOK, this is expected, and in fact looks like it was landed as part of the original Win64 EME build: https://bugzilla.mozilla.org/show_bug.cgi?id=1534522.  I'm not quite sure why these changes triggered `precomplete` differences, but since it doesn't seem to be an ongoing problem with WDBA landings, I'm not going to pursue it.",
     'count': 34,
     'id': 14921117},
    {'creation_time': '2020-08-07T21:49:08Z',
     'text': 'This feature is no longer confidential.',
     'count': 35,
     'id': 14978880}]}}}

history = {'bugs': [{'alias': 'wdba-phase1',
   'history': [{'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'jmathies@mozilla.com, jwalker@mozilla.com, pdolanjski@mozilla.com'}],
     'when': '2019-12-09T14:58:25Z',
     'who': 'rtestard@mozilla.com'},
    {'who': 'bgrinstead@mozilla.com',
     'when': '2019-12-10T17:09:29Z',
     'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'bgrinstead@mozilla.com'}]},
    {'changes': [{'removed': '',
       'added': 'mhowell@mozilla.com',
       'field_name': 'cc'}],
     'when': '2019-12-17T16:41:13Z',
     'who': 'mhowell@mozilla.com'},
    {'changes': [{'removed': 'NEW',
       'added': 'ASSIGNED',
       'field_name': 'status'},
      {'field_name': 'assigned_to',
       'added': 'mhowell@mozilla.com',
       'removed': 'nobody@mozilla.org'}],
     'when': '2020-01-24T20:39:46Z',
     'who': 'mhowell@mozilla.com'},
    {'when': '2020-01-28T18:33:11Z',
     'who': 'nalexander@mozilla.com',
     'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'nalexander@mozilla.com'}]},
    {'when': '2020-02-03T18:49:47Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'field_name': 'cc',
       'added': 'rtublitz@mozilla.com',
       'removed': ''}]},
    {'when': '2020-02-06T22:04:14Z',
     'who': 'chutten@mozilla.com',
     'changes': [{'removed': '',
       'added': 'chutten@mozilla.com',
       'field_name': 'cc'}]},
    {'who': 'mhowell@mozilla.com',
     'when': '2020-02-06T22:40:30Z',
     'changes': [{'attachment_id': 9124828,
       'field_name': 'flagtypes.name',
       'added': 'data-review?(chutten@mozilla.com)',
       'removed': ''}]},
    {'who': 'chutten@mozilla.com',
     'when': '2020-02-07T16:33:43Z',
     'changes': [{'removed': '',
       'field_name': 'flagtypes.name',
       'added': 'needinfo?(mhowell@mozilla.com)'},
      {'attachment_id': 9124828,
       'added': '',
       'field_name': 'flagtypes.name',
       'removed': 'data-review?(chutten@mozilla.com)'}]},
    {'when': '2020-02-07T17:09:56Z',
     'who': 'mhowell@mozilla.com',
     'changes': [{'field_name': 'flagtypes.name',
       'added': 'needinfo?(rtestard@mozilla.com)',
       'removed': 'needinfo?(mhowell@mozilla.com)'}]},
    {'changes': [{'field_name': 'attachments.description',
       'added': 'Bug 1602463 Part 2 - Add a pref to enable/disable the default browser agent and reflect it to the registry where the agent can read it. r=agashlin,bytesized,nalexander',
       'attachment_id': 9124831,
       'removed': 'Bug 1602463 Part 4 - Add a pref to enable/disable the default browser agent and reflect it to the registry where the agent can read it. r=agashlin,bytesized,nalexander'}],
     'when': '2020-02-08T00:55:32Z',
     'who': 'phab-bot@bmo.tld'},
    {'changes': [{'removed': 'Bug 1602463 Part 2 - Windows default browser agent. r=agashlin,bytesized,nalexander',
       'attachment_id': 9124828,
       'added': 'Bug 1602463 Part 3 - Windows default browser agent. r=agashlin,bytesized,nalexander',
       'field_name': 'attachments.description'}],
     'when': '2020-02-08T00:56:19Z',
     'who': 'phab-bot@bmo.tld'},
    {'who': 'phab-bot@bmo.tld',
     'when': '2020-02-08T00:57:09Z',
     'changes': [{'attachment_id': 9124830,
       'added': 'Bug 1602463 Part 4 - Register/unregister the default browser agent scheduled task during install/uninstall. r=agashlin,bytesized,nalexander',
       'field_name': 'attachments.description',
       'removed': 'Bug 1602463 Part 3 - Register/unregister the default browser agent scheduled task during install/uninstall. r=agashlin,bytesized,nalexander'}]},
    {'changes': [{'added': 'bzhao@mozilla.com',
       'field_name': 'cc',
       'removed': ''}],
     'who': 'bzhao@mozilla.com',
     'when': '2020-02-12T03:58:27Z'},
    {'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'emilio@crisal.io'}],
     'when': '2020-02-14T13:51:22Z',
     'who': 'emilio@crisal.io'},
    {'who': 'jcristau@mozilla.com',
     'when': '2020-03-02T10:59:59Z',
     'changes': [{'field_name': 'cc',
       'added': 'jcristau@mozilla.com',
       'removed': ''}]},
    {'who': 'tublitzed@gmail.com',
     'when': '2020-03-03T18:10:27Z',
     'changes': [{'field_name': 'priority', 'added': 'P1', 'removed': '--'},
      {'removed': 'Windows Default Browser Agent',
       'field_name': 'summary',
       'added': 'Windows Default Browser Agent - Phase 1'},
      {'removed': '---',
       'added': 'In Review',
       'field_name': 'cf_install_update_workflow'}]},
    {'when': '2020-03-03T18:17:00Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'field_name': 'see_also',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1619699',
       'removed': ''}]},
    {'when': '2020-03-09T20:57:51Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'removed': '',
       'added': 'needinfo?(chutten@mozilla.com), needinfo?(agray@mozilla.com)',
       'field_name': 'flagtypes.name'},
      {'removed': '', 'field_name': 'cc', 'added': 'agray@mozilla.com'}]},
    {'changes': [{'added': '',
       'field_name': 'flagtypes.name',
       'removed': 'needinfo?(agray@mozilla.com)'}],
     'who': 'agray@mozilla.com',
     'when': '2020-03-09T23:28:15Z'},
    {'when': '2020-03-10T13:44:34Z',
     'who': 'chutten@mozilla.com',
     'changes': [{'removed': 'needinfo?(chutten@mozilla.com)',
       'field_name': 'flagtypes.name',
       'added': ''}]},
    {'changes': [{'removed': '',
       'added': '1621293',
       'field_name': 'depends_on'}],
     'when': '2020-03-10T14:13:17Z',
     'who': 'tublitzed@gmail.com'},
    {'changes': [{'field_name': 'blocks', 'added': '1619699', 'removed': ''}],
     'who': 'nalexander@mozilla.com',
     'when': '2020-03-11T16:49:23Z'},
    {'changes': [{'added': 'smith-phase1',
       'field_name': 'alias',
       'removed': ''}],
     'who': 'nalexander@mozilla.com',
     'when': '2020-03-11T16:49:33Z'},
    {'changes': [{'removed': 'smith-phase1',
       'field_name': 'alias',
       'added': 'wdba-phase1'}],
     'who': 'nalexander@mozilla.com',
     'when': '2020-03-11T17:10:38Z'},
    {'who': 'malexandru@mozilla.com',
     'when': '2020-03-16T19:24:00Z',
     'changes': [{'added': 'needinfo?(mhowell@mozilla.com)',
       'field_name': 'flagtypes.name',
       'removed': ''}]},
    {'changes': [{'added': '',
       'field_name': 'flagtypes.name',
       'removed': 'needinfo?(mhowell@mozilla.com)'}],
     'who': 'mhowell@mozilla.com',
     'when': '2020-03-16T19:24:37Z'},
    {'when': '2020-03-16T22:26:27Z',
     'who': 'rharter@mozilla.com',
     'changes': [{'removed': '',
       'added': 'ethompson@mozilla.com, rharter@mozilla.com',
       'field_name': 'cc'}]},
    {'when': '2020-03-16T22:29:27Z',
     'who': 'nalexander@mozilla.com',
     'changes': [{'removed': '',
       'added': 'needinfo?(nalexander@mozilla.com)',
       'field_name': 'flagtypes.name'}]},
    {'changes': [{'removed': 'ASSIGNED',
       'field_name': 'status',
       'added': 'RESOLVED'},
      {'added': 'FIXED', 'field_name': 'resolution', 'removed': ''},
      {'added': 'aryx.bugmail@gmx-topmail.de',
       'field_name': 'cc',
       'removed': ''},
      {'removed': '---',
       'added': 'mozilla76',
       'field_name': 'target_milestone'},
      {'field_name': 'cf_last_resolved',
       'added': '2020-03-17T10:03:02Z',
       'removed': ''},
      {'added': 'fixed',
       'field_name': 'cf_status_firefox76',
       'removed': '---'}],
     'when': '2020-03-17T10:03:02Z',
     'who': 'aryx.bugmail@gmx-topmail.de'},
    {'when': '2020-03-17T13:45:40Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'added': 'approval-mozilla-beta?',
       'field_name': 'flagtypes.name',
       'attachment_id': 9124827,
       'removed': ''}]},
    {'when': '2020-03-17T13:45:43Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'removed': '',
       'attachment_id': 9124828,
       'field_name': 'flagtypes.name',
       'added': 'approval-mozilla-beta?'},
      {'attachment_id': 9124830,
       'field_name': 'flagtypes.name',
       'added': 'approval-mozilla-beta?',
       'removed': ''},
      {'removed': '',
       'attachment_id': 9124831,
       'field_name': 'flagtypes.name',
       'added': 'approval-mozilla-beta?'},
      {'attachment_id': 9130218,
       'field_name': 'flagtypes.name',
       'added': 'approval-mozilla-beta?',
       'removed': ''}]},
    {'changes': [{'added': '1624047',
       'field_name': 'depends_on',
       'removed': ''}],
     'when': '2020-03-20T21:55:15Z',
     'who': 'mhowell@mozilla.com'},
    {'changes': [{'removed': '',
       'field_name': 'depends_on',
       'added': '1624388'}],
     'when': '2020-03-23T18:43:04Z',
     'who': 'mhowell@mozilla.com'},
    {'changes': [{'removed': 'aryx.bugmail@gmx-topmail.de',
       'added': '',
       'field_name': 'cc'}],
     'who': 'aryx.bugmail@gmx-topmail.de',
     'when': '2020-03-24T10:23:55Z'},
    {'who': 'jcristau@mozilla.com',
     'when': '2020-03-25T18:07:04Z',
     'changes': [{'added': '',
       'field_name': 'flagtypes.name',
       'removed': 'needinfo?(rtestard@mozilla.com)'},
      {'attachment_id': 9124827,
       'added': 'approval-mozilla-beta+',
       'field_name': 'flagtypes.name',
       'removed': 'approval-mozilla-beta?'}]},
    {'when': '2020-03-25T18:07:11Z',
     'who': 'jcristau@mozilla.com',
     'changes': [{'added': 'approval-mozilla-beta+',
       'field_name': 'flagtypes.name',
       'attachment_id': 9124828,
       'removed': 'approval-mozilla-beta?'}]},
    {'who': 'jcristau@mozilla.com',
     'when': '2020-03-25T18:07:18Z',
     'changes': [{'field_name': 'flagtypes.name',
       'added': 'approval-mozilla-beta+',
       'attachment_id': 9124830,
       'removed': 'approval-mozilla-beta?'}]},
    {'changes': [{'removed': 'approval-mozilla-beta?',
       'attachment_id': 9124831,
       'added': 'approval-mozilla-beta+',
       'field_name': 'flagtypes.name'}],
     'who': 'jcristau@mozilla.com',
     'when': '2020-03-25T18:07:28Z'},
    {'when': '2020-03-25T18:07:45Z',
     'who': 'jcristau@mozilla.com',
     'changes': [{'removed': 'approval-mozilla-beta?',
       'attachment_id': 9130218,
       'field_name': 'flagtypes.name',
       'added': 'approval-mozilla-beta+'}]},
    {'changes': [{'added': 'fixed',
       'field_name': 'cf_status_firefox75',
       'removed': '---'}],
     'who': 'jcristau@mozilla.com',
     'when': '2020-03-26T08:55:30Z'},
    {'when': '2020-03-26T08:55:38Z',
     'who': 'jcristau@mozilla.com',
     'changes': [{'comment_id': 14716983,
       'comment_count': 33,
       'removed': '',
       'added': 'uplift',
       'field_name': 'comment_tag'}]},
    {'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'catalin.sasca@softvision.ro, mihai.boldan@softvision.ro, vlad.lucaci@softvision.ro'}],
     'who': 'mihai.boldan@softvision.com',
     'when': '2020-03-27T10:27:07Z'},
    {'who': 'jcristau@mozilla.com',
     'when': '2020-03-27T16:11:14Z',
     'changes': [{'field_name': 'cf_tracking_firefox_relnote',
       'added': '75+',
       'removed': '---'}]},
    {'changes': [{'removed': '',
       'added': '1626020',
       'field_name': 'depends_on'}],
     'who': 'mhowell@mozilla.com',
     'when': '2020-04-06T16:21:09Z'},
    {'changes': [{'removed': '',
       'added': '1628924',
       'field_name': 'regressions'}],
     'who': 'agashlin+bz@gmail.com',
     'when': '2020-04-10T01:27:44Z'},
    {'changes': [{'removed': '',
       'field_name': 'depends_on',
       'added': '1630410'}],
     'when': '2020-04-27T10:03:15Z',
     'who': 'dao+bmo@mozilla.com'},
    {'changes': [{'removed': '',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1636539',
       'field_name': 'see_also'}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-05-08T17:38:43Z'},
    {'changes': [{'removed': 'needinfo?(nalexander@mozilla.com)',
       'added': '',
       'field_name': 'flagtypes.name'}],
     'when': '2020-07-06T16:26:08Z',
     'who': 'nalexander@mozilla.com'},
    {'changes': [{'field_name': 'groups',
       'added': '',
       'removed': 'mozilla-employee-confidential'}],
     'who': 'nalexander@mozilla.com',
     'when': '2020-08-07T21:49:08Z'},
    {'when': '2020-12-15T23:29:55Z',
     'who': 'agashlin+bz@gmail.com',
     'changes': [{'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1682680',
       'field_name': 'see_also',
       'removed': ''}]},
    {'changes': [{'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1733984',
       'field_name': 'see_also',
       'removed': ''}],
     'who': 'chutten@mozilla.com',
     'when': '2021-10-04T16:12:59Z'},
    {'changes': [{'added': '1738211',
       'field_name': 'depends_on',
       'removed': ''}],
     'when': '2021-10-28T08:58:42Z',
     'who': 'rtestard@mozilla.com'},
    {'changes': [{'removed': 'General',
       'added': 'Default Browser Agent',
       'field_name': 'component'},
      {'removed': 'In Review',
       'field_name': 'cf_install_update_workflow',
       'added': '---'}],
     'when': '2022-06-01T17:27:48Z',
     'who': 'bytesized@mozilla.com'}],
   'id': 1602463},
  {'id': 1619699,
   'history': [{'when': '2020-03-03T18:15:11Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'field_name': 'priority', 'added': 'P3', 'removed': '--'},
      {'removed': '---',
       'field_name': 'cf_install_update_workflow',
       'added': 'Prioritized'}]},
    {'changes': [{'removed': '',
       'field_name': 'see_also',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1602463'}],
     'when': '2020-03-03T18:17:00Z',
     'who': 'tublitzed@gmail.com'},
    {'changes': [{'field_name': 'url',
       'added': 'PRD: https://docs.google.com/document/d/1WWUGCSFv3ZclY8uJsqSYNSiX330ydQbyenlZy8gLB9U/edit#',
       'removed': ''}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-03-03T20:20:12Z'},
    {'changes': [{'removed': 'nobody@mozilla.org',
       'added': 'nalexander@mozilla.com',
       'field_name': 'assigned_to'},
      {'field_name': 'status', 'added': 'ASSIGNED', 'removed': 'NEW'}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-03-04T22:06:02Z'},
    {'who': 'tublitzed@gmail.com',
     'when': '2020-03-05T14:44:09Z',
     'changes': [{'field_name': 'cc',
       'added': 'mhowell@mozilla.com, nalexander@mozilla.com',
       'removed': ''}]},
    {'changes': [{'added': 'P2', 'field_name': 'priority', 'removed': 'P3'}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-03-05T14:44:18Z'},
    {'changes': [{'field_name': 'alias',
       'added': 'smith-phase2',
       'removed': ''},
      {'removed': '', 'field_name': 'depends_on', 'added': '1602463'}],
     'when': '2020-03-11T16:49:23Z',
     'who': 'nalexander@mozilla.com'},
    {'when': '2020-03-11T17:10:13Z',
     'who': 'nalexander@mozilla.com',
     'changes': [{'removed': 'smith-phase2',
       'field_name': 'alias',
       'added': 'wdba-phase2'}]},
    {'when': '2020-03-11T17:17:51Z',
     'who': 'nalexander@mozilla.com',
     'changes': [{'added': '1621703',
       'field_name': 'depends_on',
       'removed': ''}]},
    {'when': '2020-03-17T13:49:27Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'added': 'rharter@mozilla.com',
       'field_name': 'cc',
       'removed': ''}]},
    {'changes': [{'added': 'mreid@mozilla.com',
       'field_name': 'cc',
       'removed': ''},
      {'field_name': 'flagtypes.name',
       'added': 'needinfo?(mreid@mozilla.com)',
       'removed': ''}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-03-17T13:52:43Z'},
    {'who': 'bugzilla@dblohm7.ca',
     'when': '2020-03-17T16:46:15Z',
     'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'aklotz@mozilla.com'}]},
    {'changes': [{'removed': '',
       'added': 'rtanglao@mozilla.com',
       'field_name': 'cc'}],
     'when': '2020-03-17T17:42:29Z',
     'who': 'rtanglao@mozilla.com'},
    {'changes': [{'removed': '',
       'added': 'mdroettboom@mozilla.com',
       'field_name': 'cc'},
      {'added': 'needinfo?(mdroettboom@mozilla.com)',
       'field_name': 'flagtypes.name',
       'removed': 'needinfo?(mreid@mozilla.com)'}],
     'when': '2020-03-27T13:12:03Z',
     'who': 'mreid@mozilla.com'},
    {'changes': [{'added': 'chutten@mozilla.com',
       'field_name': 'cc',
       'removed': ''},
      {'removed': 'needinfo?(mdroettboom@mozilla.com)',
       'added': 'needinfo?(chutten@mozilla.com)',
       'field_name': 'flagtypes.name'}],
     'when': '2020-03-27T16:16:45Z',
     'who': 'mdroettboom@mozilla.com'},
    {'changes': [{'field_name': 'flagtypes.name',
       'added': '',
       'removed': 'needinfo?(chutten@mozilla.com)'}],
     'who': 'chutten@mozilla.com',
     'when': '2020-03-27T17:18:54Z'},
    {'changes': [{'added': 'ksteuber@mozilla.com',
       'field_name': 'assigned_to',
       'removed': 'nalexander@mozilla.com'}],
     'when': '2020-03-31T17:02:04Z',
     'who': 'tublitzed@gmail.com'},
    {'when': '2020-04-24T14:21:52Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'added': 'P1', 'field_name': 'priority', 'removed': 'P2'}]},
    {'who': 'agashlin+bz@gmail.com',
     'when': '2020-05-05T17:12:39Z',
     'changes': [{'added': '1635507',
       'field_name': 'depends_on',
       'removed': ''}]},
    {'changes': [{'removed': '1635507',
       'field_name': 'depends_on',
       'added': ''},
      {'field_name': 'see_also',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1635507',
       'removed': ''}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-05-08T17:34:59Z'},
    {'when': '2020-05-08T17:38:43Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1636539',
       'field_name': 'see_also',
       'removed': ''}]},
    {'changes': [{'removed': '',
       'field_name': 'flagtypes.name',
       'added': 'needinfo?(l10n@mozilla.com)'},
      {'field_name': 'cc', 'added': 'l10n@mozilla.com', 'removed': ''}],
     'when': '2020-05-12T20:04:45Z',
     'who': 'bytesized@mozilla.com'},
    {'changes': [{'field_name': 'flagtypes.name',
       'added': '',
       'removed': 'needinfo?(l10n@mozilla.com)'}],
     'who': 'l10n@mozilla.com',
     'when': '2020-05-13T17:12:56Z'},
    {'when': '2020-05-13T17:31:49Z',
     'who': 'bytesized@mozilla.com',
     'changes': [{'field_name': 'flagtypes.name',
       'added': 'needinfo?(l10n@mozilla.com)',
       'removed': ''}]},
    {'when': '2020-05-13T17:48:40Z',
     'who': 'bytesized@mozilla.com',
     'changes': [{'removed': 'needinfo?(l10n@mozilla.com)',
       'field_name': 'flagtypes.name',
       'added': ''}]},
    {'who': 'tublitzed@gmail.com',
     'when': '2020-05-27T19:44:37Z',
     'changes': [{'removed': '',
       'field_name': 'depends_on',
       'added': '1636539'}]},
    {'changes': [{'removed': '',
       'field_name': 'cc',
       'added': 'jvehent@mozilla.com'}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-06-01T16:24:51Z'},
    {'who': 'tublitzed@gmail.com',
     'when': '2020-06-02T13:49:28Z',
     'changes': [{'field_name': 'see_also',
       'added': '',
       'removed': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1636539'}]},
    {'changes': [{'removed': 'PRD: https://docs.google.com/document/d/1WWUGCSFv3ZclY8uJsqSYNSiX330ydQbyenlZy8gLB9U/edit#',
       'added': 'https://docs.google.com/document/d/1WWUGCSFv3ZclY8uJsqSYNSiX330ydQbyenlZy8gLB9U/edit#',
       'field_name': 'url'}],
     'who': 'dveditz@mozilla.com',
     'when': '2020-07-23T00:06:47Z'},
    {'changes': [{'removed': '',
       'added': '1657147',
       'field_name': 'depends_on'}],
     'who': 'emil.ghitta@softvision.com',
     'when': '2020-08-04T16:06:01Z'},
    {'changes': [{'added': '1657158',
       'field_name': 'depends_on',
       'removed': ''}],
     'when': '2020-08-04T16:49:50Z',
     'who': 'emil.ghitta@softvision.com'},
    {'when': '2020-08-04T17:21:27Z',
     'who': 'emil.ghitta@softvision.com',
     'changes': [{'field_name': 'depends_on',
       'added': '1657170',
       'removed': ''}]},
    {'when': '2020-08-07T21:49:53Z',
     'who': 'nalexander@mozilla.com',
     'changes': [{'removed': 'mozilla-employee-confidential',
       'added': '',
       'field_name': 'groups'}]},
    {'who': 'mhowell@mozilla.com',
     'when': '2020-08-25T00:13:50Z',
     'changes': [{'removed': '',
       'added': '1660920',
       'field_name': 'depends_on'}]},
    {'changes': [{'removed': '1657158',
       'field_name': 'depends_on',
       'added': ''},
      {'removed': '',
       'field_name': 'see_also',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1657158'}],
     'who': 'tublitzed@gmail.com',
     'when': '2020-09-11T16:19:55Z'},
    {'when': '2020-09-11T16:20:14Z',
     'who': 'tublitzed@gmail.com',
     'changes': [{'removed': 'ASSIGNED',
       'added': 'RESOLVED',
       'field_name': 'status'},
      {'removed': '', 'field_name': 'resolution', 'added': 'FIXED'},
      {'field_name': 'cf_last_resolved',
       'added': '2020-09-11T16:20:14Z',
       'removed': ''}]},
    {'changes': [{'removed': '',
       'field_name': 'see_also',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1664510'}],
     'when': '2020-09-11T16:35:00Z',
     'who': 'tublitzed@gmail.com'},
    {'when': '2020-10-07T14:42:01Z',
     'who': 'emil.ghitta@softvision.com',
     'changes': [{'added': '1669732',
       'field_name': 'depends_on',
       'removed': ''}]},
    {'when': '2020-10-07T14:42:55Z',
     'who': 'emil.ghitta@softvision.com',
     'changes': [{'removed': '1669732',
       'field_name': 'depends_on',
       'added': ''}]},
    {'who': 'agashlin+bz@gmail.com',
     'when': '2020-12-15T23:29:55Z',
     'changes': [{'removed': '',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1682680',
       'field_name': 'see_also'}]},
    {'who': 'tublitzed@gmail.com',
     'when': '2021-01-04T22:09:14Z',
     'changes': [{'field_name': 'see_also',
       'added': 'https://bugzilla.mozilla.org/show_bug.cgi?id=1684971',
       'removed': ''}]},
    {'changes': [{'field_name': 'component',
       'added': 'Default Browser Agent',
       'removed': 'General'},
      {'field_name': 'cf_install_update_workflow',
       'added': '---',
       'removed': 'Prioritized'}],
     'who': 'bytesized@mozilla.com',
     'when': '2022-06-01T17:33:36Z'}],
   'alias': 'wdba-phase2'}]}

attachment = {'attachments': {},
 'bugs': {'1602463': [{'content_type': 'text/x-phabricator-request',
    'is_patch': 0,
    'flags': [{'id': 1957496,
      'status': '+',
      'modification_date': '2020-03-25T18:07:04Z',
      'type_id': 721,
      'name': 'approval-mozilla-beta',
      'setter': 'jcristau@mozilla.com',
      'creation_date': '2020-03-17T13:45:40Z'}],
    'creation_time': '2020-02-06T19:31:54Z',
    'file_name': 'phabricator-D61888-url.txt',
    'id': 9124827},
   {'id': 9124828,
    'file_name': 'phabricator-D61889-url.txt',
    'flags': [{'creation_date': '2020-03-17T13:45:43Z',
      'name': 'approval-mozilla-beta',
      'status': '+',
      'setter': 'jcristau@mozilla.com',
      'id': 1957497,
      'type_id': 721,
      'modification_date': '2020-03-25T18:07:11Z'}],
    'creation_time': '2020-02-06T19:33:56Z',
    'is_patch': 0,
    'content_type': 'text/x-phabricator-request'},
   {'is_patch': 0,
    'content_type': 'text/x-phabricator-request',
    'file_name': 'phabricator-D61891-url.txt',
    'id': 9124830,
    'creation_time': '2020-02-06T19:36:14Z',
    'flags': [{'setter': 'jcristau@mozilla.com',
      'id': 1957498,
      'type_id': 721,
      'modification_date': '2020-03-25T18:07:18Z',
      'creation_date': '2020-03-17T13:45:43Z',
      'name': 'approval-mozilla-beta',
      'status': '+'}]},
   {'is_patch': 0,
    'content_type': 'text/x-phabricator-request',
    'file_name': 'phabricator-D61892-url.txt',
    'id': 9124831,
    'creation_time': '2020-02-06T19:38:47Z',
    'flags': [{'type_id': 721,
      'modification_date': '2020-03-25T18:07:28Z',
      'id': 1957499,
      'setter': 'jcristau@mozilla.com',
      'status': '+',
      'creation_date': '2020-03-17T13:45:43Z',
      'name': 'approval-mozilla-beta'}]},
   {'file_name': 'phabricator-D64992-url.txt',
    'id': 9130218,
    'creation_time': '2020-03-02T18:49:10Z',
    'flags': [{'name': 'approval-mozilla-beta',
      'setter': 'jcristau@mozilla.com',
      'creation_date': '2020-03-17T13:45:43Z',
      'id': 1957500,
      'status': '+',
      'modification_date': '2020-03-25T18:07:45Z',
      'type_id': 721}],
    'is_patch': 0,
    'content_type': 'text/x-phabricator-request'}],
  '1619699': []}}
