from pydantic import BaseModel, Field


class GeneratedReviewComment(BaseModel):
    """A review comment generated by the code review agent."""

    file: str = Field(description="The path to the file the comment applies to.")
    code_line: int = Field(description="The line number that the comment refers to.")
    comment: str = Field(description="The review comment.")
    explanation: str = Field(
        description="A brief rationale for the comment, including how confident you are and why."
    )
    order: int = Field(
        description="An integer representing the priority of the comment, with 1 being the highest confidence/importance."
    )


class AgentResponse(BaseModel):
    """The response from the code review agent."""

    comments: list[GeneratedReviewComment] = Field(
        description="A list of generated review comments."
    )
