import re

import httpx
import tenacity
from pydantic import BaseModel, Field, PrivateAttr

from bugbug.tools.core.connection import get_http_client
from bugbug.tools.core.data_types import InlineComment


class GeneratedReviewComment(BaseModel):
    """A review comment generated by the code review agent."""

    file: str = Field(description="The path to the file the comment applies to.")
    code_line: int = Field(description="The line number that the comment refers to.")
    comment: str = Field(description="The review comment.")
    explanation: str = Field(
        description="A brief rationale for the comment, including how confident you are and why."
    )
    order: int = Field(
        description="An integer representing the priority of the comment, with 1 being the highest confidence/importance."
    )


class AgentResponse(BaseModel):
    """The response from the code review agent."""

    comments: list[GeneratedReviewComment] = Field(
        description="A list of generated review comments."
    )


class CodeReviewToolResponse(BaseModel):
    """The response from the CodeReviewTool."""

    review_comments: list[InlineComment] = Field(
        description="A list of inline comments to be added to the code review, converted from the agent's generated comments."
    )
    patch_summary: str = Field(
        description="A brief summary of the patch, generated by the agent."
    )
    details: dict = Field(
        description="Additional details about the tool's execution, such as which models were used and any relevant metadata."
    )


class SkillLoadError(Exception):
    """Raised when a Skill's body cannot be loaded."""


_FRONTMATTER_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.DOTALL)


def _strip_frontmatter(text: str) -> str:
    return _FRONTMATTER_RE.sub("", text, count=1)


class Skill(BaseModel):
    """A reusable instruction set the agent can load on demand."""

    name: str = Field(
        description="A unique identifier the agent uses to load the skill."
    )
    url: str = Field(description="HTTPS URL of the skill.md file.")
    description: str = Field(
        description="Short summary shown to the agent so it can decide when to load this skill."
    )

    _cached_body: str | None = PrivateAttr(default=None)

    async def load(self) -> str:
        """Return the skill body, fetching and caching it on first use."""
        if self._cached_body is not None:
            return self._cached_body

        try:
            response = await get_http_client().get(self.url, timeout=30)
            response.raise_for_status()
        except httpx.HTTPError as e:
            raise SkillLoadError(
                f"Could not load skill '{self.name}' from {self.url}"
            ) from e

        self._cached_body = _strip_frontmatter(response.text)
        return self._cached_body


class ExternalContentLoadError(Exception):
    """Raised when an ExternalContent body cannot be loaded."""


@tenacity.retry(
    stop=tenacity.stop_after_attempt(3),
    wait=tenacity.wait_exponential(multiplier=1, min=1),
    retry=tenacity.retry_if_exception_type(httpx.TransportError),
    reraise=True,
)
async def _fetch_url(url: str) -> httpx.Response:
    response = await get_http_client().get(url, timeout=30)
    response.raise_for_status()
    return response


class ExternalContent(BaseModel):
    """An external file fetched and injected as context for the review."""

    name: str = Field(description="A unique identifier for this content item.")
    url: str = Field(description="HTTPS URL of the file to fetch.")
    description: str = Field(
        description="Short description of what this content provides."
    )

    _cached_body: str | None = PrivateAttr(default=None)

    async def load(self) -> str:
        """Return the content body, fetching and caching it on first use."""
        if self._cached_body is not None:
            return self._cached_body

        try:
            response = await _fetch_url(self.url)
        except httpx.HTTPError as e:
            raise ExternalContentLoadError(
                f"Could not load content '{self.name}' from {self.url}"
            ) from e

        self._cached_body = _strip_frontmatter(response.text)
        return self._cached_body
