# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

"""Performance alerts data pipeline.

Extracts Perfherder alerts, pushes and perf job coverage from the Treeherder
replica exposed by STMO, task costs from BigQuery ``fxci`` and regression bugs
from Bugzilla, and derives labeled datasets for performance test selection and
performance regression prediction. Importing this package registers every
dataset with ``bugbug.db``.
"""

from bugbug.perf.datasets import (
    PERF_ALERT_BUGS_DB,
    PERF_ALERTS_DB,
    PERF_PAIRS_DB,
    PERF_PUSH_STATUS_DB,
    PERF_PUSHES_DB,
    PERF_REGRESSION_COMMITS_DB,
    PERF_REGRESSIONS_DB,
    PERF_TASK_COSTS_DB,
    get_perf_alert_bugs,
    get_perf_alerts,
    get_perf_pairs,
    get_perf_push_status,
    get_perf_pushes,
    get_perf_regression_commits,
    get_perf_regressions,
    get_perf_task_costs,
)
from bugbug.perf.extraction import (
    BIGQUERY_DATA_SOURCE_ID,
    COST_FIELDS,
    RECORD_SEP,
    TREEHERDER_DATA_SOURCE_ID,
    UNIT_SEP,
    build_alerts_query,
    build_pushes_query,
    build_task_costs_query,
    fetch_alerts,
    fetch_bugs,
    fetch_pushes,
    fetch_task_costs,
    merge_alerts,
    normalize_alert_row,
    normalize_cost_row,
    parse_push_row,
)
from bugbug.perf.label_policy import (
    CATEGORY_RULES,
    CONFIRMED_BUG_RESOLUTIONS,
    EXCLUDED_FRAMEWORKS,
    FIREFOX_APPLICATIONS,
    PLATFORM_RENAMES,
    POLICY_VERSION,
    POSITIVE_OUTCOMES,
    REJECTED_BUG_RESOLUTIONS,
    REPOSITORIES,
)
from bugbug.perf.push_status import (
    generate_push_status,
    get_push_commits,
    get_push_label_states,
    is_within_labeled_window,
    iter_clean_commits,
    read_push_status,
)
from bugbug.perf.regression_commits import (
    assign_train_test_splits,
    attach_commit_patches,
    parse_hg_export,
    select_export_commits,
)
from bugbug.perf.regression_labeling import (
    PushIndex,
    alert_is_positive,
    check_regressed_by_agreement,
    decide_regression_outcome,
    generate_regressions,
    get_landing_id,
    get_ran_perf_labels,
    group_landings,
    is_within_window,
    pin_culprit_commits,
    resolve_canonical_bug,
    summary_is_confirmed,
)
from bugbug.perf.selection_pairs import generate_scheduling_pairs, iter_labeled_pairs
from bugbug.perf.task_costs import (
    LabelPrice,
    TaskCost,
    build_label_prices,
    collect_push_task_ids,
    estimate_labels_cost,
    load_task_costs,
    summarize_push_cost,
)
from bugbug.perf.task_labels import (
    get_exclusion_reason,
    get_platform_family,
    get_runnable_identity,
    get_test_category,
    is_perf_task_label,
    normalize_platform,
    normalize_task_label,
    split_task_label,
    split_test_name,
)

__all__ = [
    "BIGQUERY_DATA_SOURCE_ID",
    "CATEGORY_RULES",
    "CONFIRMED_BUG_RESOLUTIONS",
    "COST_FIELDS",
    "EXCLUDED_FRAMEWORKS",
    "FIREFOX_APPLICATIONS",
    "LabelPrice",
    "PERF_ALERTS_DB",
    "PERF_ALERT_BUGS_DB",
    "PERF_PAIRS_DB",
    "PERF_PUSHES_DB",
    "PERF_PUSH_STATUS_DB",
    "PERF_REGRESSIONS_DB",
    "PERF_REGRESSION_COMMITS_DB",
    "PERF_TASK_COSTS_DB",
    "PLATFORM_RENAMES",
    "POLICY_VERSION",
    "POSITIVE_OUTCOMES",
    "PushIndex",
    "RECORD_SEP",
    "REJECTED_BUG_RESOLUTIONS",
    "REPOSITORIES",
    "TREEHERDER_DATA_SOURCE_ID",
    "TaskCost",
    "UNIT_SEP",
    "alert_is_positive",
    "assign_train_test_splits",
    "attach_commit_patches",
    "build_alerts_query",
    "build_label_prices",
    "build_pushes_query",
    "build_task_costs_query",
    "check_regressed_by_agreement",
    "collect_push_task_ids",
    "decide_regression_outcome",
    "estimate_labels_cost",
    "fetch_alerts",
    "fetch_bugs",
    "fetch_pushes",
    "fetch_task_costs",
    "generate_push_status",
    "generate_regressions",
    "generate_scheduling_pairs",
    "get_exclusion_reason",
    "get_landing_id",
    "get_perf_alert_bugs",
    "get_perf_alerts",
    "get_perf_pairs",
    "get_perf_push_status",
    "get_perf_pushes",
    "get_perf_regression_commits",
    "get_perf_regressions",
    "get_perf_task_costs",
    "get_platform_family",
    "get_push_commits",
    "get_push_label_states",
    "get_ran_perf_labels",
    "get_runnable_identity",
    "get_test_category",
    "group_landings",
    "is_perf_task_label",
    "is_within_labeled_window",
    "is_within_window",
    "iter_clean_commits",
    "iter_labeled_pairs",
    "load_task_costs",
    "merge_alerts",
    "normalize_alert_row",
    "normalize_cost_row",
    "normalize_platform",
    "normalize_task_label",
    "parse_hg_export",
    "parse_push_row",
    "pin_culprit_commits",
    "read_push_status",
    "resolve_canonical_bug",
    "select_export_commits",
    "split_task_label",
    "split_test_name",
    "summarize_push_cost",
    "summary_is_confirmed",
]
