name: Docker build & push
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - id: gcp-auth
        name: Google authentication
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          service_account: artifact-writer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Generate version.json
        shell: bash
        run: |
          printf '{"commit":"%s","version":"%s","source":"https://github.com/%s","build":"%s/%s/actions/runs/%s"}\n' \
          "$GITHUB_SHA" \
          "$GITHUB_REF_NAME" \
          "$GITHUB_REPOSITORY" \
          "$GITHUB_SERVER_URL" \
          "$GITHUB_REPOSITORY" \
          "$GITHUB_RUN_ID" | tee version.json
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}
      - name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: ./http_service/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/bugbug-http-service:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
      - name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: ./http_service/Dockerfile.bg_worker
          push: ${{ github.event_name != 'pull_request' }}
          sbom: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/bugbug-http-service-bg-worker:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
